# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-10 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kubecluster',
            name='node_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_online',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='version_env',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_physical_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='port_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versionenv',
            name='deploy_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versionenv',
            name='image_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
