# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-10 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s_manager', '0002_auto_20190110_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_online',
            field=models.DateField(blank=True, null=True),
        ),
    ]
