# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-11 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s_manager', '0003_auto_20190110_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubeconfig',
            name='deploy',
            field=models.CharField(blank=True, choices=[(b'yes', b'yes'), (b'no', b'no')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='kubeconfig',
            name='deploy_mode',
            field=models.CharField(choices=[(b'allinone', b'allinone'), (b'single-master', b'single-master'), (b'multi-master', b'multi-master')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kubeconfig',
            name='etcd_node',
            field=models.CharField(max_length=150, verbose_name='etcd\u8282\u70b9'),
        ),
        migrations.AlterField(
            model_name='kubeconfig',
            name='harbor_node',
            field=models.CharField(max_length=40, verbose_name='harbor\u8282\u70b9'),
        ),
        migrations.AlterField(
            model_name='kubeconfig',
            name='kube_master',
            field=models.CharField(max_length=150, verbose_name='\u96c6\u7fa4master\u8282\u70b9'),
        ),
        migrations.AlterField(
            model_name='kubeconfig',
            name='kube_node',
            field=models.CharField(max_length=150, verbose_name='\u96c6\u7fa4node\u8282\u70b9'),
        ),
        migrations.AlterField(
            model_name='kubeconfig',
            name='kube_version',
            field=models.CharField(choices=[(b'v1.8', b'v1.8'), (b'v1.9', b'v1.9'), (b'v1.10', b'v1.10'), (b'v1.11', b'v1.11'), (b'v1.12', b'v1.12')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kubeconfig',
            name='lb_node',
            field=models.CharField(max_length=50, verbose_name='\u8d1f\u8f7d\u5747\u8861\u8282\u70b9'),
        ),
    ]
